export { PlayerComponent } from './player/player.component'
export { EditPlayerComponent } from './player/edit/edit.component'
export { PlayersComponent } from './players/genre/players.component'
export { LoginComponent } from './user/login/login.component'
export { RegisterComponent } from './user/register/register.component'
